First off all you need to obtain your Kaggle **username** and **key token** like it is show in this guide: <https://www.analyticsvidhya.com/blog/2021/04/how-to-download-kaggle-datasets-using-jupyter-notebook/>

In [1]:
import opendatasets as od

URL = 'https://www.kaggle.com/prathamsharma123/farmers-protest-tweets-dataset-raw-json'
od.download(URL)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: josepoke
Your Kaggle Key: ········
Downloading farmers-protest-tweets-dataset-raw-json.zip to .\farmers-protest-tweets-dataset-raw-json

100%|███████████████████████████████████████████████████████████████████████████████| 191M/191M [00:37<00:00, 5.36MB/s]

In [2]:
import os

PATH = 'farmers-protest-tweets-dataset-raw-json'
if os.path.isdir(PATH):
    os.rename(PATH, 'db')

In [3]:
import pandas as pd

df = pd.read_json('db/farmers-protest-tweets-2021-03-5.json', lines=True)
df['username'] = df['user'].apply(lambda x: x['username'])
df.rename(columns = {'date':'datetime'}, inplace = True)
df.head()

,url,datetime,content,renderedContent,id,user,outlinks,tcooutlinks,replyCount,retweetCount,...,conversationId,lang,source,sourceUrl,sourceLabel,media,retweetedTweet,quotedTweet,mentionedUsers,username
0,https://twitter.com/ShashiRajbhar6/status/1376...,2021-03-30 03:33:46+00:00,Support 👇\n\n#FarmersProtest,Support 👇\n\n#FarmersProtest,1376739399593910273,"{'username': 'ShashiRajbhar6', 'displayname': ...",[],[],0,0,...,1376739399593910273,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None,ShashiRajbhar6
1,https://twitter.com/kaursuk06272818/status/137...,2021-03-30 03:33:23+00:00,Supporting farmers means supporting our countr...,Supporting farmers means supporting our countr...,1376739306287427584,"{'username': 'kaursuk06272818', 'displayname':...",[],[],0,0,...,1376739306287427584,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,[{'previewUrl': 'https://pbs.twimg.com/media/E...,NaN,None,None,kaursuk06272818
2,https://twitter.com/kaursuk06272818/status/137...,2021-03-30 03:31:00+00:00,Support farmers if you are related to food #St...,Support farmers if you are related to food #St...,1376738704128020488,"{'username': 'kaursuk06272818', 'displayname':...",[],[],0,0,...,1376738704128020488,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,[{'previewUrl': 'https://pbs.twimg.com/media/E...,NaN,None,None,kaursuk06272818
3,https://twitter.com/SukhdevSingh_/status/13767...,2021-03-30 03:30:45+00:00,#StopHateAgainstFarmers support #FarmersProtes...,#StopHateAgainstFarmers support #FarmersProtes...,1376738640542400518,"{'username': 'SukhdevSingh_', 'displayname': '...",[],[],0,1,...,1376738640542400518,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None,SukhdevSingh_
4,https://twitter.com/Davidmu66668113/status/137...,2021-03-30 03:30:30+00:00,"You hate farmers I hate you, \nif you love the...","You hate farmers I hate you, \nif you love the...",1376738579171344386,"{'username': 'Davidmu66668113', 'displayname':...",[],[],0,0,...,1376738579171344386,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None,Davidmu66668113

**1)** Top 10 retweeted tweets

In [4]:
def top_10_retweeted_tweets(df):
    return df.sort_values(by=['retweetCount'], ascending=False)[['username', 'retweetCount', 'content']][0:10]

top_10_retweeted_tweets(df)

,username,retweetCount,content
408128,rihanna,315547,why aren’t we talking about this?! #FarmersPro...
395142,GretaThunberg,103957,We stand in solidarity with the #FarmersProtes...
266196,GretaThunberg,67694,I still #StandWithFarmers and support their pe...
366579,miakhalifa,35921,"“Paid actors,” huh? Quite the casting director..."
372793,miakhalifa,26972,What in the human rights violations is going o...
314192,TeamJuJu,23251,"Happy to share that I’ve donated $10,000 to pr..."
215034,BobBlackman,20132,There has been much social media coverage arou...
398011,vanessa_vash,18744,Farmers feed the world. Fight for them. Protec...
325261,kylekuzma,17368,Should be talking about this! #FarmersProtest\...
163689,AmandaCerny,15677,To all of my influencer/celeb friends- read up...

**2)** Top 10 users who tweet the most

In [5]:
def make_serie_into_df(s, column_0):
    return pd.DataFrame([s.index, s.values]).T.rename(columns = {0: column_0, 1: 'number_of_tweets'})

In [6]:
def top_10_users_with_most_tweets(df):
    answer_in_serie = df.groupby(['username'])['username'].count().sort_values(ascending=False)
    return make_serie_into_df(answer_in_serie, column_0='username')[0:10]

top_10_users_with_most_tweets(df)

          username number_of_tweets
0  harjot_tweeting             7134
1    tasveersandhu             2091
2  shells_n_petals             1991
3           jot__b             1841
4    rebelpacifist             1806
5         rumsomal             1722
6      Iamjazzie96             1502
7         Jass_k_G             1460
8  DigitalKisanBot             1453
9    z_khalique007             1446

**3)** Top 10 most active days

In [7]:
def top_10_active_days(df):
    df['date'] = df['datetime'].apply(lambda x: x.date())
    answer_in_serie = df.groupby(['date'])['date'].count().sort_values(ascending=False)
    return make_serie_into_df(answer_in_serie, column_0='date')[0:10]

top_10_active_days(df)

         date number_of_tweets
0  2021-02-03            83866
1  2021-02-04            58607
2  2021-02-05            33332
3  2021-02-02            28548
4  2021-02-06            22420
5  2021-02-07            11325
6  2021-02-09             9320
7  2021-02-08             8920
8  2021-02-10             7973
9  2021-02-11             5698

**4)** Top 10 more used hashtags

In [8]:
import re

def top_10_hashtags_more_used(df):
    df['hashtag'] = df['renderedContent'].apply(lambda x: re.findall(r"#(\w+)", x))
    
    hashtag_counter = {}
    def count_hashtags(list_):
        for element in list_:
            if element not in hashtag_counter:
                hashtag_counter[element] = 1
            else:
                hashtag_counter[element] += 1
    df['hashtag'].apply(count_hashtags)

    dictlist = [ [key, value] for key, value in hashtag_counter.items() ]
    dictlist.sort(key=lambda x: x[1], reverse=True)
    
    df_hashtags = pd.DataFrame(dictlist).rename(columns = {0: 'hashtag', 1: 'number_of_tweets'})
    return df_hashtags[0:10]

top_10_hashtags_more_used(df)

                    hashtag  number_of_tweets
0            FarmersProtest            406613
1         IStandWithFarmers             15783
2            farmersprotest             15458
3  IndianFarmersHumanRights             12019
4           FarmersAreIndia             11043
5          StandWithFarmers             10645
6                   Rihanna              9117
7           FarmersProtests              8750
8                   Farmers              6561
9          shameonbollywood              6270

In [9]:
def validate_input(int_input):
    try:
        if int(int_input) not in list(range(1, 5)):
            int_input = input("Please enter a valid option.\n> ")
            return validate_input(int_input)
        return int(int_input)
    except ValueError:
        int_input = input("Please enter a valid option.\n> ")
        return validate_input(int_input)


def main():
    if True:
        options_str = """Available functions:
    [1] Top 10 most retweeted tweets
    [2] Top 10 users that tweeted the most
    [3] Top 10 most active days
    [4] Top 10 most used hashtags"""
    
        functions_dict = [top_10_retweeted_tweets,
                          top_10_users_with_most_tweets,
                          top_10_active_days,
                          top_10_hashtags_more_used]

        selected_function = validate_input(input(f"{options_str}\n> "))
        result = functions_dict[selected_function - 1](df)
        print("Execution result:\n")
        return result

In [ ]:
if __name__ == "__main__":
    main()